version: "{build}"

platform: x64

branches:
    only:
      - master

clone_depth: 10

skip_tags: true

environment:
  RECRUE_TEST_PACKAGES:

  matrix:
  - SOLDAT_CHANNEL: stable
  - SOLDAT_CHANNEL: beta

install:
  - ps: Install-Product node 4

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/DavidLemarier/ci/master/build-package.ps1'))

test: off
deploy: off
